---
- name: Create Ubuntu VM
  connection: local
  hosts: localhost
  roles:
    - role: prerequisites
    - role: download_ubuntu
    - role: cloud_init
    - role: create_vm_qemu_image
    - role: create_vm
    - role: vm_ip
    # - role: delete_vm
  vars:
    vm_name: ubuntu
    vm_vcpus: 2
    vm_ram_gb: 2
    disk_size: 10G
    ubuntu_version: noble
