---
- name: Create Ubuntu VM
  connection: local
  hosts: localhost
  roles:
    # - role: download_ubuntu
    # - role: create_vm_qemu_image
    # - role: generate_cloud_init_iso
    # - role: create_vm
    # - role: vm_ip
    # - role: delete_vm
  vars:
    vm_name: "ubuntu"
    vm_vcpus: 1
    vm_ram_mb: 1024
