---
- name: Create Ubuntu VM
  connection: local
  hosts: localhost
  roles:
    - role: download_ubuntu
    # - role: kvm_provision
    # - role: list
  vars:
    ansible_user: "mint"
    vm_name: "ubuntu"
    vm_vcpus: 1
    vm_ram_mb: 1024
