---
- name: Generate Cloud Init ISO
  become: yes
  command: |
    genisoimage -output {{ libvirt_pool_dir }}/cidata.iso
      -V cidata -r -J
      roles/cloud_init/files/user-data
      roles/cloud_init/files/meta-data
