- name: Check if ubuntu image exists
  stat:
    path: "{{ ubuntu_image_path }}"
  register: image_result

- name: Download Ubuntu image
  when: not image_result.stat.exists
  become: yes
  get_url:
    url: https://cloud-images.ubuntu.com/{{ ubuntu_version }}/current/{{ ubuntu_image }}
    dest: "{{ ubuntu_image_path }}"
