---
- name: Install libvirt
  become: yes
  apt:
    update_cache: yes
    pkg:
      - python3-pip
      - qemu-kvm
      - libvirt-daemon-system
      - libguestfs-tools
      - python3-libvirt
      - genisoimage
      - virtinst

- name: Add user to libvirt group
  become: yes
  ignore_errors: yes
  user:
    name: "{{ ansible_env.USER }}"
    groups: libvirt
    append: yes

- name: Install libvirt python packages
  become: yes
  pip:
    name:
      - libvirt-python
      - lxml
